#!/bin/bash
###############################################
# install                                     #
#                                             #
#    This script, called by an EC2 instance   #
# at first launch, sets up the development    #
# environment.                                #
###############################################

set -x

# Copy over dotfiles from this repo
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cat ${DIR}/.gitconfig >> ~/.gitconfig
cat ${DIR}/.bash_aliases >> ~/.bash_aliases
cat ${DIR}/.tmux.conf >> ~/.tmux.conf
rsync -az ${DIR}/.ssh ~/

exit 0
